name: example
description: A new Flutter project.

version: 1.0.0+1

publish_to: none

environment:
  flutter: '>=3.0.2'
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  spine_flutter_dart:
    path: ../

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/cake/
    - assets/cake/cake/
    - assets/cake/images/
    - assets/car/
    - assets/car/car/
    - assets/car/images/
    - assets/cat/
    - assets/cat/cat/
    - assets/cat/images/
    - assets/cup/
    - assets/cup/cup/
    - assets/cup/images/

    - assets/U10-L3-1-b-girl_5/
    - assets/U10-L3-1-b-girl_5/Girl/
    - assets/U10-L3-1-b-girl_5/images/
    - assets/TA3_U4_Sing/
    - assets/TA3_U4_Sing/TA3_U4_Sing/
    - assets/TA3_U4_Sing/images/
    - assets/BeBill/
    - assets/BeBill/BeBill/
    - assets/BeBill/images/

