name: example
description: A new Flutter project.

version: 1.0.0+1

publish_to: none

environment:
  flutter: '>=3.0.2'
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  spine_flutter_dart:
    path: ../

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/cauldron/
    - assets/fox/
    - assets/girl_and_whale_polygons/
    - assets/girl_and_whale_rectangles/
    - assets/owl/
    - assets/raptor/
    - assets/spineboy/
