# author Junji Takakura <j.takakura@gmail.com>

name: spine_flutter_dart
description: The spine-flutter runtime provides functionality to load and manipulate Spine skeletal animation data using Flutter.
version: 0.2.0
homepage: https://github.com/jtakakura/spine_flutter/

environment:
  flutter: '>=3.0.2'
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  spine_core: ^0.3.5

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
